import { StyleSheet } from 'react-native';
import colors from 'styles/colors';

export default StyleSheet.create({
  container: { flex: 1, paddingHorizontal: 16 },
  sectionTitle: {
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    color: colors.faint,
    marginTop: 18,
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  rowMain: { flex: 1 },
  name: { fontSize: 15, fontWeight: '600', color: colors.heading },
  sub: { fontSize: 12, color: colors.faint, marginTop: 2 },
  roleTag: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 999,
    overflow: 'hidden',
    marginRight: 10,
  },
  owner: { backgroundColor: colors.surface2, color: colors.heading },
  agent: { backgroundColor: colors.surface2, color: colors.body },
  remove: { color: colors.error[400], fontWeight: '600', fontSize: 14, paddingHorizontal: 4 },
  searchInput: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 12,
    backgroundColor: colors.surface,
    padding: 12,
    fontSize: 15,
    color: colors.heading,
  },
  addBtn: { color: colors.secondary[600], fontWeight: '700', fontSize: 14, paddingHorizontal: 4 },
  hint: { fontSize: 13, color: colors.faint, marginTop: 6 },
  loader: { marginTop: 24 },
});
